apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveries-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efood
      service: deliveries
  template:
    metadata:
      labels:
        app: efood
        service: deliveries
        sidecar.istio.io/inject: "true"
        version: "1"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: deliveries
        image: ghcr.io/wofood/efood_deliveries
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - name: deliveries
            protocol: TCP
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: efood-config
