apiVersion: v1
kind: Service
metadata:
  name: deliveries-svc
  labels:
    app: efood
    service: deliveries
spec:
  selector:
    app: efood
    service: deliveries
  ports:
    - name: http-port
      port: 3000
