import { Injectable } from '@nestjs/common';

@Injectable()
export class DeliveriesMultipleDummyService {
  dummyOrderDelivery() {
    return {
      status: 'success',
      message: 'Berhasil membuat order.',
      data: {
        id: '20915f8c-0553-485c-867b-f10d79f26ad4',
        airway_bill: 'ELN13012111600001',
        tracking_url:
          'https://dev.elog.co.id/tracking/20915f8c-0553-485c-867b-f10d79f26ad4',
        delivery_type: 'INSTANT',
        status: 'CONFIRMED',
        pickup_destinations: [
          {
            id: 'fd301087-32fe-4504-a4a8-351c31596f80',
            longitude: 107.59653259049831,
            latitude: -6.877444678496585,
            contact_name: 'Richeese Factory Flamboyan ',
            contact_phone: '6282214863662',
            address:
              'Jl. Sukajadi No.234, Gegerkalong, Kec. Sukasari, Kota Bandung, Jawa Barat 40153',
            address_name: 'Richeese Factory Flamboyan ',
            location_description: '',
            note: '',
            destination_order: 0,
            items: [
              {
                name: 'Combo Rich Burger - Beef',
                weight: 1,
                quantity: 1,
                price: 48000,
                note: null,
              },
            ],
            external_id: null,
          },
        ],
        dropoff_destinations: [
          {
            id: 'c34d3a23-1040-46d5-b078-3d2d4307bb2a',
            longitude: 107.5785705,
            latitude: -6.8905558,
            contact_name: 'Fatkhur Roni',
            contact_phone: '6285648636747',
            address:
              'WU Tower, Jalan Doktor Djunjunan, Sukawarna, Bandung City, West Java, Indonesia',
            address_name: 'kantor',
            location_description: '',
            note: '',
            destination_order: 1,
          },
        ],
      },
    };
  }

  dummyOrderFailed() {
    return {
      status: 'error',
      error: 'ERR_NOT_FOUND',
      message: 'Tidak dapat menemukan pengemudi di sekitar anda',
      data: null,
    };
  }

  dummyNatsData(id) {
    return {
      // group_id: 'b11eb0be-2f6f-4e96-bf73-8f4aefd3164f',
      group_id: id,
      logistic_platform: 'ELOG',
      courier_id: '1e9449bd-d5f9-4cf2-bba5-126a86b0b21e',
      customer_id: 'ebb6d6dd-0285-4ee9-8828-b1b2ae2593cd',
      customer_address: {
        id: '784c2bf0-d1f7-4fee-942a-6c2fc5c3a306',
        name: 'kantor',
        address:
          'WU Tower, Jalan Doktor Djunjunan, Sukawarna, Bandung City, West Java, Indonesia',
        location_latitude: -6.8905558,
        location_longitude: 107.5785705,
        address_detail: '',
        postal_code: '40164',
        created_at: '2022-11-09T09:59:13.597Z',
        updated_at: '2022-11-09T09:59:13.611Z',
        deleted_at: null,
      },
      delivery_type: 'DELIVERY',
      ongkir: 3300,
      orders: [
        {
          id: '03e58eda-dd70-459f-b888-e151aee8fb6a',
          no: 'EF410',
          store_id: '65313ee4-ed18-4950-ab5b-9441beb57c78',
          merchant_id: 'b828bd80-fe6d-451c-86ed-f8e1850b84ad',
          cart_payload: [
            {
              uniqId: 'cb056007-bca5-47d0-bd4a-9455ce3207ef',
              quantity: 1,
              menu: {
                id: 'd8b6a482-a26b-43de-bf2f-d2cb07b2afd7',
                photo:
                  'https://dev-api-efood.akarinti.tech/api/v1/orders/order/03e58eda-dd70-459f-b888-e151aee8fb6a/0/image/1659295241869-image.png',
                name: 'Combo 1 Fire Chicken',
                description:
                  '1 Fire Chicken + 1 Nasi + 1 Medium Drink + cheese sauce',
                status: null,
                recomendation: true,
                merchant_id: 'b828bd80-fe6d-451c-86ed-f8e1850b84ad',
                sequence: null,
                created_at: null,
                updated_at: null,
                store_avilability_id: null,
                store_id: '65313ee4-ed18-4950-ab5b-9441beb57c78',
                sales_channel_id: '362ced7a-883d-4a32-b2de-c1e209ba64ad',
                menu_prices: [],
                menu_price: [
                  {
                    id: 'c3a20db2-20a1-4fd0-973c-7fd2d0a51a66',
                    price: 49000,
                    menu_category_prices: null,
                    menu_sales_channels: null,
                    menu_category_price: null,
                    menu_sales_channel: null,
                  },
                ],
                variations: null,
                menu_variations: [
                  {
                    id: '778fc711-c6f1-46e4-b98a-ea8d3f5ca4fb',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'c9c09e22-ca78-40d4-848f-ac0a468ebc5a',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '0b3bc959-3df1-4f1f-8f91-b17e2f4b5f4e',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'e54987eb-3fa8-46a5-93a8-552ac3e80f46',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'b1db0928-b59e-4391-b106-8bbe83fc76d3',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '58283d9d-e977-4a3a-8b36-6fdeb33f9910',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '1cc73756-d478-4af6-9de0-c2bc99715747',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '6579f5a1-33ba-45c0-8012-e4739de2f976',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '4c7f2382-9a8b-4f74-9cdf-598bd1785733',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '87e57e31-313a-4b35-97da-f2cce2e39600',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'adda4b4a-0111-46be-9d64-913d5e88b9a4',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'fc91dad2-2e80-47c3-815f-eacf9cb7b68a',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'ecc4e11b-155e-447d-853f-f9614338b20d',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '6c5206cd-93ee-426d-b7a0-f7228a2ba037',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '4098b318-e4b9-415e-aa1a-e1cfbeede428',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '2a87b815-8a44-42e9-b69a-716ddcda5d9d',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'a773aa9c-0087-49ca-8a14-2d0eaf582720',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'd12b2a3d-8865-40f8-b636-a4f9540f9738',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'd961e6fe-3251-4410-9990-6eec288f8566',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '70cdcf0a-cdb0-4575-b280-115095422f38',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'c6ce2431-2acf-48a9-a632-3ec9c1304a1d',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'dbaa8cd8-ef45-4862-8142-4e0f7748bfda',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'e4ed169f-f2f6-4464-94e3-c70b7165d4c5',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '81e8b911-405c-4c0a-a79c-9c7b18d92cb4',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'c56910c8-dc00-4f93-9473-e9b347bedd20',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'd6079137-7d9d-4d4b-9da2-c24699d4420b',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'd7f30784-98ed-4a17-a56f-5a229b2f539c',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '0feeb254-38ce-474d-8718-e1fb33883be9',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '753825ca-4523-43ab-8df1-8238dd6b02bf',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'c708c86a-baf6-4e43-9f4d-8f97e965cab9',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '34fedb89-531d-4f60-893d-43252db20721',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '4d6df2d4-fd8e-47ba-aec1-bbd1c8406e4f',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'a1edbd17-d321-414e-be8f-b5933dc8d041',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'f3cf2ff9-2081-4a96-9081-3b628aca65fb',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'ca1422df-89a6-44a7-8ada-9eea96112182',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '47b983be-6fb6-4a55-aa9b-6a028a53c5cb',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'c78e8971-e768-4346-aa7b-4cad620c9248',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'aadf6465-8dcf-4b83-bb42-ad29016cba03',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '4e4eeec4-26fc-4395-8b93-5d779fa55e1f',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: '91412b9d-8321-4b75-ad7d-bd22ca0cfc46',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'e72af487-8d24-4da9-aa8a-0213e549f1ea',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                  {
                    id: 'b24f5901-d452-4b10-b6d9-02e9cdf07796',
                    name: null,
                    description: null,
                    mandatory: null,
                    is_combo_menu: null,
                    limitation: null,
                    variation: null,
                    menus: null,
                  },
                ],
                stock_available: true,
                discounted_price: 39200,
                original_price: 49000,
                price: 49000,
                menu_sales_channel_stocks: [],
                type: 'COMBO',
              },
              storeAvilabiltyId: null,
              variantSelected: [
                {
                  id: 'ac41516e-494d-473b-83c8-0618a24e11d2',
                  name: '1 OR Fire Chicken ',
                  price: 0,
                  quantity: 1,
                  sequence: 0,
                  qty: null,
                  idSection: 'de0e364a-8fca-456e-93cf-d9e5ace14045',
                  nameSection: 'Fire Chicken 1pcs',
                  is_combo_menu: false,
                  is_default_menu: true,
                },
                {
                  id: '59e441d3-6ecd-4f86-a957-b435c07e02c4',
                  name: 'Rice',
                  price: 0,
                  quantity: 1,
                  sequence: 0,
                  qty: null,
                  idSection: 'a146f8b8-d580-4d2c-a259-c06154ffddf4',
                  nameSection: 'Rice',
                  is_combo_menu: false,
                  is_default_menu: null,
                },
                {
                  id: '5f324c1f-a33f-46f2-add0-44dd96efc053',
                  name: 'Dipisah ',
                  price: 0,
                  quantity: 1,
                  sequence: 0,
                  qty: null,
                  idSection: 'c3693beb-95b6-4d9b-8a02-cb42c075a076',
                  nameSection: 'Penyajian BBQ Sauce',
                  is_combo_menu: false,
                  is_default_menu: null,
                },
                {
                  id: '3da8978b-2a1e-472b-9849-092a4d475464',
                  name: 'Tropical Fusion',
                  price: 0,
                  quantity: 1,
                  sequence: 1,
                  qty: null,
                  idSection: '93c1cab3-3f48-4e44-ab06-8b6c1eea6e49',
                  nameSection: 'Medium Drink ',
                  is_combo_menu: false,
                  is_default_menu: null,
                },
                {
                  id: 'ffba24a2-4b74-4314-9fc8-7a8ad77c0d88',
                  name: 'Level 0',
                  price: 0,
                  quantity: 1,
                  sequence: 0,
                  qty: null,
                  idSection: 'e09d28a4-523f-4d57-b9ad-e6423fb8e010',
                  nameSection: 'Level BBQ Sauce ',
                  is_combo_menu: false,
                  is_default_menu: null,
                },
              ],
              note: '',
              price: 39200,
              original_price: 49000,
              priceTotal: 39200,
              addOns: [],
              discounted_price: 39200,
              totalPrice: 39200,
            },
          ],
        },
        {
          id: 'd84db0c3-f96c-4c94-bffe-5c15078295d1',
          no: 'EF421',
          store_id: 'b5133d61-9e57-44fe-946e-a5b88bc56798',
          merchant_id: '1cee088c-21bc-41dc-9b50-290374c2c315',
          cart_payload: [
            {
              uniqId: '73b10bd2-9578-4eee-9f48-2d65ace3c109',
              quantity: 1,
              menu: {
                id: 'cb261a74-a2df-4750-89f7-5466c30a756e',
                photo:
                  'https://dev-api-efood.akarinti.tech/api/v1/orders/order/d84db0c3-f96c-4c94-bffe-5c15078295d1/0/image/1657621103535-image.png',
                name: 'Usus',
                description: 'Satuan usus',
                status: null,
                recomendation: true,
                merchant_id: '1cee088c-21bc-41dc-9b50-290374c2c315',
                sequence: null,
                created_at: null,
                updated_at: null,
                store_avilability_id: null,
                store_id: 'b5133d61-9e57-44fe-946e-a5b88bc56798',
                sales_channel_id: '19acae53-afca-4465-be33-b43e50b1b4fd',
                menu_prices: [],
                menu_price: [
                  {
                    id: '35d7e023-f8ea-4af5-ac85-1d63d90b2959',
                    price: 2000,
                    menu_category_prices: null,
                    menu_sales_channels: null,
                    menu_category_price: null,
                    menu_sales_channel: null,
                  },
                ],
                variations: null,
                menu_variations: [],
                stock_available: true,
                discounted_price: null,
                original_price: null,
                price: 2000,
                menu_sales_channel_stocks: [],
                type: null,
              },
              storeAvilabiltyId: null,
              variantSelected: [],
              note: '',
              price: 2000,
              original_price: null,
              priceTotal: 2000,
              addOns: [],
              discounted_price: null,
              totalPrice: 2000,
            },
            {
              uniqId: 'd7dca1fa-edf0-4935-b436-ce8c72be9f1e',
              quantity: 1,
              menu: {
                id: '9c55b1e1-3548-4067-a3b5-8125d2957083',
                photo:
                  'https://dev-api-efood.akarinti.tech/api/v1/orders/order/d84db0c3-f96c-4c94-bffe-5c15078295d1/1/image/ffffff&text=Photo+Menu',
                name: 'Nasi goreng',
                description: 'Nasi goreng gurih',
                status: null,
                recomendation: true,
                merchant_id: '1cee088c-21bc-41dc-9b50-290374c2c315',
                sequence: null,
                created_at: null,
                updated_at: null,
                store_avilability_id: null,
                store_id: 'b5133d61-9e57-44fe-946e-a5b88bc56798',
                sales_channel_id: '19acae53-afca-4465-be33-b43e50b1b4fd',
                menu_prices: [],
                menu_price: [
                  {
                    id: '4eaf490b-6210-4833-ae1c-43f8b574c447',
                    price: 18700,
                    menu_category_prices: null,
                    menu_sales_channels: null,
                    menu_category_price: null,
                    menu_sales_channel: null,
                  },
                ],
                variations: null,
                menu_variations: [],
                stock_available: true,
                discounted_price: null,
                original_price: null,
                price: 18700,
                menu_sales_channel_stocks: [],
                type: null,
              },
              storeAvilabiltyId: null,
              variantSelected: [],
              note: '',
              price: 18700,
              original_price: null,
              priceTotal: 18700,
              addOns: [],
              discounted_price: null,
              totalPrice: 18700,
            },
          ],
        },
      ],
    };
  }

  dummyElogData() {
    return {
      pickup_destinations: [
        {
          latitude: -6.877444678496585,
          longitude: 107.59653259049833,
          address:
            'Jl. Sukajadi No.234, Gegerkalong, Kec. Sukasari, Kota Bandung, Jawa Barat 40153',
          address_name: 'Richeese Factory Flamboyan ',
          contact_phone_no: '6282214863662',
          contact_name: 'Richeese Factory Flamboyan ',
          note: '',
          location_description: '',
          items: [
            {
              name: 'Combo Rich Burger - Beef',
              price: 48000,
              weight: 1,
              quantity: 1,
            },
          ],
        },
      ],
      dropoff_destinations: [
        {
          longitude: 107.5785705,
          latitude: -6.8905558,
          contact_name: 'luthfi Satria Ramdhani',
          contact_phone_no: '6285695551507',
          address:
            'WU Tower, Jalan Doktor Djunjunan, Sukawarna, Bandung City, West Java, Indonesia',
          address_name: 'kantor',
          location_description: '',
          note: '',
        },
      ],
      price: 15300,
    };
  }
}
